=== HarsanyiBalazs/HD9DOJ_XMLGyak/HD9DOJ_1011/HD9DOJ_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">



<xs:element name="hallgato"  type="hallgatoTipus" />

<xs:element name="kurzusok">
<xs:complexType>
    <xs:sequence>
        <xs:element name="kurzus" minOccurs="0" maxOccurs="unbounded" >
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="kurzusnev" type="xs:string" />
                    <xs:element name="kredit" type="kreditTipus" />
                    <xs:element name="hely" type="xs:string" />
                    <xs:element name="idopont" type="xs:string" />
                    <xs:element name="oktato" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="oraado" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="id" type="idTipus" />
                <xs:attribute name="jovahagyas" type="jovahagyasTipus" />
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="HD9DOJ_kurzusfelvetel">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="hallgato" />
            <xs:element ref="kurzusok" />
        </xs:sequence>
        <xs:attribute name="tanev" type="tanevTipus" />
        <xs:attribute name="egyetem" type="xs:string" />
    </xs:complexType>
</xs:element>

<xs:complexType name="hallgatoTipus">
    <xs:sequence>
        <xs:element name="hnev" type="xs:string" />
        <xs:element name="szulev" type="xs:string" />
        <xs:element name="szak" type="xs:string" />
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="tanevTipus">
    <xs:restriction base="xs:int">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="5" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="kreditTipus">
    <xs:restriction base="xs:int">
        <xs:enumeration value="0" />
        <xs:enumeration value="2" />
        <xs:enumeration value="3" />
        <xs:enumeration value="4" />
        <xs:enumeration value="5" />
        <xs:enumeration value="15" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="idTipus">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{5}[0-9]{3}-B" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="jovahagyasTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="igen" />
        <xs:enumeration value="nem" />
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== HarsanyiBalazs/HD9DOJ_XMLGyak/HD9DOJ_1011/HD9DOJ_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<HD9DOJ_kurzusfelvetel xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="HD9DOJ_kurzusfelvetel.xsd" tanev="3" egyetem="Miskolci Egyetem">

    <hallgato>
        <hnev>Harsányi Balázs</hnev>
        <szulev>2001-10-15</szulev>
        <szak>programtervező informatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL304-B" jovahagyas="igen">
            <kurzusnev>Számítógép hálózatok</kurzusnev>
            <kredit>5</kredit>
            <hely>II. ea</hely>
            <idopont>szerda 8-10</idopont>
            <oktato>Dr. Kovács Szilveszter</oktato>
        </kurzus>
        <kurzus id="GEIAK130-B" jovahagyas="igen">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII. ea</hely>
            <idopont>kedd 10-12</idopont>
            <oktato>Fazekas Levente Áron</oktato>
        </kurzus>
        <kurzus id="GEIAL331-B" jovahagyas="igen">
            <kurzusnev>Web technológiák 1</kurzusnev>
            <kredit>5</kredit>
            <hely>XXX. ea</hely>
            <idopont>hétfő 14-16</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEMAK234-B" jovahagyas="igen">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>320</hely>
            <idopont>kedd 14-16</idopont>
            <oktato>Dr. Házy Attila</oktato>
        </kurzus>
        <kurzus id="GEIAL332-B" jovahagyas="igen">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXX. ea</hely>
            <idopont>kedd 12-14</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEIAL315-B" jovahagyas="igen">
            <kurzusnev>Vállalati információs rendszerek fejlesztése</kurzusnev>
            <kredit>5</kredit>
            <hely>101 inf</hely>
            <idopont>szerda 14-16</idopont>
            <oktato>Dr. Sasvári Péter László</oktato>
        </kurzus>
        <kurzus id="GEMAK232-B" jovahagyas="igen">
            <kurzusnev>Valószínűség-számítás</kurzusnev>
            <kredit>5</kredit>
            <hely>320</hely>
            <idopont>hétfő 10-12</idopont>
            <oktato>Dr. Fegyverneki Sándor</oktato>
        </kurzus>
    </kurzusok>

</HD9DOJ_kurzusfelvetel>
