<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HarsanyiBalazs_orarend [
<!ELEMENT HarsanyiBalazs_orarend (ora)*>
<!ELEMENT ora (targy,idopont,helyszin,oktato,szak) >
<!ELEMENT targy (#PCDATA)>
<!ELEMENT idopont (nap,tol,ig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ATTLIST ora id ID #REQUIRED>
<!ATTLIST ora tipus CDATA #REQUIRED>
]>

<HarsanyiBalazs_orarend>
    <ora id="t01" tipus="elmelet">
        <targy>
            Valószínűség számítás
        </targy>
        <idopont>
            <nap>
                Hétfő
            </nap>
            <tol>
                10:00
            </tol>
            <ig>
                12:00
            </ig>
        </idopont>
        <helyszin>
            A/1 320.
        </helyszin>
        <oktato>
            Dr. Fegyverneki Sándor
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t02" tipus="elmelet">
        <targy>
            Web technológiák 1
        </targy>
        <idopont>
            <nap>
                Hétfő
            </nap>
            <tol>
                14:00
            </tol>
            <ig>
                16:00
            </ig>
        </idopont>
        <helyszin>
            A/1 XXX előadó
        </helyszin>
        <oktato>
            Agárdi Anita
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t03" tipus="gyakorlat">
        <targy>
            Web technológiák 1
        </targy>
        <idopont>
            <nap>
                Hétfő
            </nap>
            <tol>
                16:00
            </tol>
            <ig>
                18:00
            </ig>
        </idopont>
        <helyszin>
            Inf 202.
        </helyszin>
        <oktato>
            Agárdi Anita
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t04" tipus="elmelet">
        <targy>
            Mesterséges intelligencia alapok
        </targy>
        <idopont>
            <nap>
                Kedd
            </nap>
            <tol>
                10:00
            </tol>
            <ig>
                12:00
            </ig>
        </idopont>
        <helyszin>
            A/1 XXXII előadó
        </helyszin>
        <oktato>
            Kunné Dr. Tamás Judit, Fazekas Levente Áron, Huszák Péter
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t05" tipus="elmelet">
        <targy>
            Adatkezelés XML-ben
        </targy>
        <idopont>
            <nap>
                Kedd
            </nap>
            <tol>
                12:00
            </tol>
            <ig>
                14:00
            </ig>
        </idopont>
        <helyszin>
            A/1 XXXII előadó
        </helyszin>
        <oktato>
            Dr. Bednarik László
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t06" tipus="elmelet">
        <targy>
            Algoritmusok és vizsgálatuk
        </targy>
        <idopont>
            <nap>
                Kedd
            </nap>
            <tol>
                14:00
            </tol>
            <ig>
                16:00
            </ig>
        </idopont>
        <helyszin>
            A/1 320.
        </helyszin>
        <oktato>
            Dr. Házy Attila
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t07" tipus="gyakorlat">
        <targy>
            Algoritmusok és vizsgálatuk
        </targy>
        <idopont>
            <nap>
                Kedd
            </nap>
            <tol>
                16:00
            </tol>
            <ig>
                18:00
            </ig>
        </idopont>
        <helyszin>
            A/1 320.
        </helyszin>
        <oktato>
            Dr. Házy Attila
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t08" tipus="elmelet">
        <targy>
            Számítógép hálózatok
        </targy>
        <idopont>
            <nap>
                Szerda
            </nap>
            <tol>
                8:00
            </tol>
            <ig>
                10:00
            </ig>
        </idopont>
        <helyszin>
            A/2 II előadó
        </helyszin>
        <oktato>
            Dr. Kovács Szilveszter
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t09" tipus="gyakorlat">
        <targy>
            Valószínűség számítás
        </targy>
        <idopont>
            <nap>
                Szerda
            </nap>
            <tol>
                10:00
            </tol>
            <ig>
                12:00
            </ig>
        </idopont>
        <helyszin>
            A/2 312.
        </helyszin>
        <oktato>
            Dr. Túri József
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t10" tipus="gyakorlat">
        <targy>
            Adatkezelés XML-ben
        </targy>
        <idopont>
            <nap>
                Szerda
            </nap>
            <tol>
                12:00
            </tol>
            <ig>
                14:00
            </ig>
        </idopont>
        <helyszin>
            Inf 103.
        </helyszin>
        <oktato>
            Dr. Bednarik László
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t11" tipus="elmelet">
        <targy>
            Vállalati információs rendszerek fejlesztése
        </targy>
        <idopont>
            <nap>
                Szerda
            </nap>
            <tol>
                14:00
            </tol>
            <ig>
                16:00
            </ig>
        </idopont>
        <helyszin>
            Inf 101.
        </helyszin>
        <oktato>
            Dr. Sasvári Péter László
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t12" tipus="gyakorlat">
        <targy>
            Vállalati információs rendszerek fejlesztése
        </targy>
        <idopont>
            <nap>
                Szerda
            </nap>
            <tol>
                18:00
            </tol>
            <ig>
                20:00
            </ig>
        </idopont>
        <helyszin>
            Inf 101.
        </helyszin>
        <oktato>
            Dr. Sasvári Péter László
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t13" tipus="gyakorlat">
        <targy>
            Mesterséges intelligencia alapok
        </targy>
        <idopont>
            <nap>
                Csütörtök
            </nap>
            <tol>
                10:00
            </tol>
            <ig>
                12:00
            </ig>
        </idopont>
        <helyszin>
            A/2 I előadó
        </helyszin>
        <oktato>
            Fazekas Levente Áron
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>

    <ora id="t14" tipus="gyakorlat">
        <targy>
            Számítógép hálózatok
        </targy>
        <idopont>
            <nap>
                Csütörtök
            </nap>
            <tol>
                12:00
            </tol>
            <ig>
                14:00
            </ig>
        </idopont>
        <helyszin>
            A/4 III előadó
        </helyszin>
        <oktato>
            Dr. Kovács Szilveszter
        </oktato>
        <szak>
            Programtervező informatikus
        </szak>
    </ora>
</HarsanyiBalazs_orarend>