=== HarsanyiBalazs/HD9DOJ_XMLGyak/HD9DOJ_1004/HD9DOJ_ertodtd.dtd
<!ELEMENT HD9DOJ_modell (A,B,C,AB)+ >
<!ELEMENT A (b*,c+)>
<!ELEMENT b (x,y)+>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT c (d,e)+>
<!ELEMENT d (#PCDATA)>
<!ELEMENT e (#PCDATA)>
<!ELEMENT B (b)+ >
<!ELEMENT C (b2)+>
<!ELEMENT b2 (#PCDATA)>
<!ELEMENT AB (c2)+>
<!ELEMENT c2 (#PCDATA)>
<!ATTLIST A a ID #REQUIRED>
<!ATTLIST B a ID #REQUIRED>
<!ATTLIST C a ID #REQUIRED>
<!ATTLIST B cref IDREF #REQUIRED>
<!ATTLIST AB aref IDREF #REQUIRED>
<!ATTLIST AB bref IDREF #REQUIRED>

=== HarsanyiBalazs/HD9DOJ_XMLGyak/HD9DOJ_1004/HD9DOJ_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HD9DOJ_modell SYSTEM "HD9DOJ_ertodtd.dtd" >

<HD9DOJ_modell>
    <A a="a">
        <b>
            <x></x>
            <y></y>
        </b>
        <c>
            <d></d>
            <e></e>
        </c>
    </A>
    <B a="b" cref="c">
        <b>
            <x></x>
            <y></y>
        </b>
    </B>
    <C a="c">
        <b2></b2>
    </C>
    <AB aref="a" bref="b">
        <c2></c2>
    </AB>
</HD9DOJ_modell>
